### ISSUE TITLE
编译时的这样错误怎么解决呢？ 十分感谢

### ISSUE THREAD

**Issue by danielzph** [dongjing3309/minisam#1]
CMake Error at CMakeLists.txt:101 (get_target_property):
  get_target_property() called with non-existent target "Sophus::Sophus".

**Comment by lvzhaoyang** [comment]
Do you have the up-to-date Sophus? An old version of Sophus would have this issue. The recent one should be OK. 

To work this the old version, you can comment out this line in the CMake file, which worked for me.

**Comment by danielzph** [comment]
Thank you very much !    but i don't know how to comment out it in the CMakelist... could you teach me...   or how to update?  thank you!

**Comment by kintzhao** [comment]
I have the same question,  which version of sophus is necessary ?  my sophus is a621ff2e56c56c839a6c40418d42c  .



1. when i do with readme, cmake with:
------------
-- Search Dependency: Sophus
CMake Error at CMakeLists.txt:101 (get_target_property):
  get_target_property() called with non-existent target "Sophus::Sophus".
------------
2.  when i ignore the line of 101 in CMakeLists.txt..   camke with error
-----------------
[ 43%] Building CXX object minisam/CMakeFiles/minisam.dir/geometry/projection.cpp.o
In file included from /home/yhzhao/test_git/minisam/minisam/geometry/projection.cpp:9:0:
/home/yhzhao/test_git/minisam/minisam/geometry/projection.h:13:26: fatal error: sophus/se3.hpp: No such file or directory
compilation terminated.
------------
