### ISSUE TITLE
Empty python package after compilation

### ISSUE THREAD

**Issue by ChenHoy** [dongjing3309/minisam#16]
Hello,
I am compiling minisam with python3.7 and fullfill all the relevant dependencies. All tests are passed after compilation and I can import the package in Python. 

However, when importing the python package, it is empty. 

Therefore I can't run the python examples because all relevant functions are missing. What am I doing wrong?

**Comment by ChenHoy** [comment]
Ok, I did not run the setup.py because I am an idiot. Everything's working now.

**Comment by XMU-qcj** [comment]
> 好的，我没有运行 setup.py 因为我是个白痴。现在一切正常。

I'm sorry to bother you, I'm having the same problem as you, may I ask how the setup.py you mentioned is running?
