### ISSUE TITLE
Syntax Error in "setup_no_sophus.py.in"

### ISSUE THREAD

**Issue by kimsooyoung** [dongjing3309/minisam#17]
https://github.com/dongjing3309/minisam/blob/ef84796fa11ac6e5e4d4aa9d60d9b94a99a973fb/python/setup_no_sophus.py.in#L7

I think one bracket doesn't have it's pair :/
This occurs error during `make install`

```
 package_data={'minisam': ['${MINISAM_WRAPPER_FILE_NAME}', 'libminisam*', 'minisam*'] ] } ) 
```

**Comment by Lishen1** [comment]
It is. fixed in https://github.com/dongjing3309/minisam/pull/22. but anyway it will not work without Sophus dependency.
