### ISSUE TITLE
problem during installation 

### ISSUE THREAD

**Issue by josemoragaposselt** [dongjing3309/minisam#20]
Hey: I am trying to install miniSAM but appears an error during the installation: 

![miniSAM_error](https://user-images.githubusercontent.com/88406657/128090113-e67f865a-44ab-4102-b22b-108eb1963c5e.png)

thanks for your help !

**Comment by sharma-n** [comment]
Hi @josemoragaposselt,
I face the same issue as you. I'm guessing you're using GCC >9.0 which throws this error. The workaround I found for this is to add this in the `cmake` command:

`cmake ..  -D CMAKE_CXX_FLAGS="-Wno-error=deprecated-copy"`

**Comment by josemoragaposselt** [comment]
Thanks
 It works when I run Cmake with that flag.
